---
  url: https://sfg.taxonworks.org/api/v1

  # Isoptera Species File (has more data, good for testing)
  # project_token: CkxD15vOFrXd-kq2QchPig

  # PERC
  # project_token: ekMTicbZWijqmdpHKqs_TA

  # Tenebrionidae that Aaron has worked on (avoiding things that are also in MX)
  project_token: FV3se0XDYEdAQH_2pojdGA
