---
  project_name: Search PERC
  project_citation: Search PERC. 2024. https://ag.purdue.edu/department/entm/perc/
  project_url: https://github.com/PurdueEntomologicalResearchCollection/taxonpages/
  project_authors: Aaron Smith, Christopher Wirth
